services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - db.env
    volumes:
      - .:/core
    restart: "no"  

  nginx:
    image: nginx:latest
    volumes:
      - ./staticfiles:/staticfiles  
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "80:80"
    depends_on:
      - web