# Generated by Django 5.1.7 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
